### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by artooro** [devtron-labs/silver-surfer#3] opened 2021-09-23 18:20 UTC
When running kubedd with no arguments I get a panic:

```
goroutine 1 [running]:
github.com/devtron-labs/silver-surfer/pkg.(*Cluster).ServerVersion(0xc0001b3940)
	/go/src/silver-surfer/pkg/Cluster.go:60 +0x18
github.com/devtron-labs/silver-surfer/kubedd.ValidateCluster(0x0, 0xc00046e8c0)
	/go/src/silver-surfer/kubedd/kubedd.go:95 +0x145
main.processCluster()
	/go/src/silver-surfer/main.go:168 +0x251
main.glob..func1(0x2b2a240, {0x2b6f4c8, 0x0, 0x0})
	/go/src/silver-surfer/main.go:108 +0x12c
github.com/spf13/cobra.(*Command).execute(0x2b2a240, {0xc000198240, 0x0, 0x0})
	/go/src/silver-surfer/vendor/github.com/spf13/cobra/command.go:766 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x2b2a240)
	/go/src/silver-surfer/vendor/github.com/spf13/cobra/command.go:852 +0x2dc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/silver-surfer/vendor/github.com/spf13/cobra/command.go:800
main.Execute()
	/go/src/silver-surfer/main.go:258 +0x25
main.main()
	/go/src/silver-surfer/main.go:286 +0x17
```

**Comment by Meroje** [comment] 2021-09-24 15:52
stumbled on this same stacktrace, in my case it's caused by a silent failure on https://github.com/devtron-labs/silver-surfer/blob/086224d8d4ec6fe2ddf753bc872250e5afcd6cb5/pkg/Cluster.go#L42-L45 caused by my usage of file path for `certificate-authority` instead of embedding the base64.
I can have it work by disabling the `DoNotResolvePaths` option, no idea if that's desirable for everyone and worth a PR.
```patch
diff --git i/pkg/Cluster.go w/pkg/Cluster.go
index 133a7bc..63d3b03 100644
--- i/pkg/Cluster.go
+++ w/pkg/Cluster.go
@@ -28,6 +28,7 @@ type Cluster struct {
 func NewCluster(kubeconfig string, kubecontext string) *Cluster {
 	cluster := Cluster{}
 	pathOptions := clientcmd.NewDefaultPathOptions()
+	pathOptions.LoadingRules.DoNotResolvePaths = false
 	if len(kubeconfig) != 0 {
 		pathOptions.GlobalFile = kubeconfig
 	}

```

**Comment by pghildiyal** [comment] 2021-09-28 04:57
We should take this as an argument and by default keep this true, let me know if you would like to raise PR for this. Also can you panic in case of errors?

Thanks

**Comment by xtavras** [comment] 2021-09-28 08:54
I have same error running against GKE (v1.21.4-gke.301)

```sh
kubedd --target-kubernetes-version 1.22                                                                       
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12c0c56]

goroutine 1 [running]:
github.com/devtron-labs/silver-surfer/pkg.(*Cluster).ServerVersion(0x0, 0x7ffd1931df26, 0x4, 0x0, 0x0)
	/home/skopp/temp/kubedd/silver-surfer/pkg/Cluster.go:60 +0x26
github.com/devtron-labs/silver-surfer/kubedd.ValidateCluster(0x0, 0xc0003aa8c0, 0x0, 0x0, 0x0, 0x14c95e0, 0x0)
	/home/skopp/temp/kubedd/silver-surfer/kubedd/kubedd.go:95 +0x116
main.processCluster(0x168ec19)
	/home/skopp/temp/kubedd/silver-surfer/main.go:168 +0x104
main.glob..func1(0x23b1e80, 0xc000364640, 0x0, 0x2)
	/home/skopp/temp/kubedd/silver-surfer/main.go:108 +0x109
github.com/spf13/cobra.(*Command).execute(0x23b1e80, 0xc00003c190, 0x2, 0x2, 0x23b1e80, 0xc00003c190)
	/home/skopp/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20180820174524-ff0d02e85550/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x23b1e80, 0x40754f, 0xc0000480b8, 0x0)
	/home/skopp/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20180820174524-ff0d02e85550/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/home/skopp/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20180820174524-ff0d02e85550/command.go:800
main.Execute()
	/home/skopp/temp/kubedd/silver-surfer/main.go:258 +0x2d
main.main()
	/home/skopp/temp/kubedd/silver-surfer/main.go:286 +0x20
```

No issues running same command against on-prem cluster (1.19, deployed with kubespray).

**Comment by Meroje** [comment] 2021-09-28 09:08
> We should take this as an argument and by default keep this true, let me know if you would like to raise PR for this. Also can you panic in case of errors?
> 
> Thanks

I can send a PR your way for the resolvepaths arg in a few days but meanwhile I think you should cut a release with the panic, it would help to get accurate reports.

**Comment by pghildiyal** [comment] 2021-09-28 12:35
added the panic statement and released 

@artooro can you please run the latest release and share the error message

**Comment by artooro** [comment] 2021-09-28 14:19
@pghildiyal sure I just pulled the latest changes and now getting this error:
```
panic: no Auth Provider found for name "gcp"
```

I've scanned the cluster using `kubent` without any issues.

**Comment by Meroje** [comment] 2021-09-28 14:47
should be fixed by importing [`_ "k8s.io/client-go/plugin/pkg/client/auth"`](https://github.com/trankchung/kubeswitch/commit/93495c71505dd9b9e562a7a85e0f68f227869969)

**Comment by xtavras** [comment] 2021-09-28 15:03
@Meroje can confirm, it works now with GKE.

**Comment by pghildiyal** [comment] 2021-09-28 15:04
@Meroje awesome, can you send the PR?  😄

**Comment by xtavras** [comment] 2021-09-28 15:16
@pghildiyal This PR uses same file https://github.com/devtron-labs/silver-surfer/pull/7

**Comment by pghildiyal** [comment] 2021-09-28 15:29
@xtavras Thanks, changes looked fine to me and have merged them. 
I will wait for auth changes also before releasing the binaries.

**Closed** 2021-09-29 17:19 UTC
